[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
zksync_sepolia = "https://sepolia.era.zksync.dev"

[etherscan]
zksync_sepolia = { key = "no-api-key-required", url = "https://sepolia.explorer.zksync.io" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
